services:
  keuanganku-be:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pamjaya-be
    restart: always
    env_file: .env
    ports:
      - "3001:4001"  # Host 3001 -> Container 4001 [KOREKSI]
      - "5555:5555"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - e-daily-report-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/api/health"] # Port 4001 [KOREKSI]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  e-daily-report-net:
    external: true
    name: e-daily-report_default
